---
- name: Namespace alkalmazasa
  shell: microk8s kubectl create namespace {{ k8s_namespace }} --dry-run=client -o yaml | microk8s kubectl apply --validate=false -f -
  changed_when: true

- name: ConfigMap letrehozasa
  shell: microk8s kubectl create configmap mikrocsirip-config --namespace {{ k8s_namespace }} --from-literal=frontend-url="http://localhost:{{ frontend_port }}" --dry-run=client -o yaml | microk8s kubectl apply --validate=false -f -
  changed_when: true

- name: Namespace kesz
  debug:
    msg: "OK Namespace {{ k8s_namespace }} kesz"
